spring:
    application:
        name: user-microservice
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://localhost:8888
            name: user-microservice